class SeedData {
  SeedData._();

  static const List<Map<String, dynamic>> defaultUsers = [
    {
      'user_id': 'admin-01',
      'name': 'Fandom Commander',
      'email': 'admin@fandomverse.com',
      'role': 'admin',
      'avatar_url': 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
      'bio': 'Lead Operations Administrator & Content Overseer',
      'badges': '["Admin Commander", "System Architect"]',
      'selected_fandoms': '["All"]',
      'created_at': 1700000000000,
    },
    {
      'user_id': 'fan-01',
      'name': 'Alex Mercer',
      'email': 'fan@fandomverse.com',
      'role': 'fan',
      'avatar_url': 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400',
      'bio': 'Anime watcher, speedrunner & convention fanatic.',
      'badges': '["Master Lorekeeper", "Con Veteran 2025"]',
      'selected_fandoms': '["Anime & Manga", "Gaming & Esports"]',
      'created_at': 1700000000000,
    },
  ];

  static const List<Map<String, dynamic>> defaultCategories = [
    {
      'category_id': 'cat_anime',
      'name': 'Anime & Manga',
      'description': 'Cosplay, Graphic Novels, Shonen & Seinen lore primers.',
      'icon_name': 'auto_awesome',
      'banner_url': 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800',
      'color_hex': '#9C27B0',
    },
    {
      'category_id': 'cat_gaming',
      'name': 'Gaming & Esports',
      'description': 'Speedruns, open-world RPG builds, competitive tournament meta.',
      'icon_name': 'sports_esports',
      'banner_url': 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800',
      'color_hex': '#00E676',
    },
    {
      'category_id': 'cat_scifi',
      'name': 'Sci-Fi & Fantasy',
      'description': 'Space operas, cybernetic lore, multi-century chronicles.',
      'icon_name': 'rocket_launch',
      'banner_url': 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800',
      'color_hex': '#00E5FF',
    },
    {
      'category_id': 'cat_comics',
      'name': 'Marvel & DC Comics',
      'description': 'Multiverse timelines, superhero dynasties, crossover arcs.',
      'icon_name': 'menu_book',
      'banner_url': 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800',
      'color_hex': '#FF1744',
    },
    {
      'category_id': 'cat_kpop',
      'name': 'K-Pop & Idol Culture',
      'description': 'Discographies, world tours, official lightsticks, member bios.',
      'icon_name': 'music_note',
      'banner_url': 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800',
      'color_hex': '#FF4081',
    },
    {
      'category_id': 'cat_movies',
      'name': 'Pop Culture & Movies',
      'description': 'Cinematic sagas, film festival debuts, directors cuts.',
      'icon_name': 'movie',
      'banner_url': 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800',
      'color_hex': '#FF9100',
    },
  ];

  static const List<Map<String, dynamic>> defaultMerchandise = [
    {
      'product_id': 'prod-001',
      'name': 'Chrono Blade Neon Katana (Replica 1:1)',
      'category': 'Replica Props',
      'price': 149.99,
      'original_price': 189.99,
      'image_url': 'https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=600',
      'description': 'Forged high-density carbon alloy blade with interactive RGB LED edge lighting and display stand. Officially licensed.',
      'stock_count': 6,
      'rating': 4.9,
      'is_featured': 1,
    },
    {
      'product_id': 'prod-002',
      'name': 'Cyber Otaku Oversized Hoodie [Night City]',
      'category': 'Apparel',
      'price': 69.50,
      'original_price': 85.00,
      'image_url': 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600',
      'description': 'Heavyweight 450 GSM French Terry cotton hoodie with reflective typography print and hidden thumb cuffs.',
      'stock_count': 18,
      'rating': 4.8,
      'is_featured': 1,
    },
    {
      'product_id': 'prod-003',
      'name': 'Valkyrie Prime Action Figure (Articulated)',
      'category': 'Action Figures',
      'price': 89.00,
      'original_price': 110.00,
      'image_url': 'https://images.unsplash.com/photo-1608889175123-8ee362201f81?w=600',
      'description': 'Over 32 points of articulation with interchangeable hands, energy wings, and battle-damaged armor plates.',
      'stock_count': 4,
      'rating': 5.0,
      'is_featured': 1,
    },
    {
      'product_id': 'prod-004',
      'name': 'Infinite Multiverse Hardcover Omnibus Vol. 1',
      'category': 'Manga/Comics',
      'price': 54.99,
      'original_price': 65.00,
      'image_url': 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600',
      'description': 'Over 850 pages collecting the legendary multiverse collision arc with exclusive author commentary and sketches.',
      'stock_count': 22,
      'rating': 4.7,
      'is_featured': 0,
    },
    {
      'product_id': 'prod-005',
      'name': 'Aero-Glow Smart Idol Lightstick v3',
      'category': 'Digital Collectibles',
      'price': 42.00,
      'original_price': 50.00,
      'image_url': 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600',
      'description': 'Bluetooth synced concert lightstick capable of 16M colors with concert arena proximity sync protocol.',
      'stock_count': 35,
      'rating': 4.9,
      'is_featured': 1,
    },
    {
      'product_id': 'prod-006',
      'name': 'Mecha G-Zero Collector Enamel Pin Set',
      'category': 'Digital Collectibles',
      'price': 24.99,
      'original_price': 30.00,
      'image_url': 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600',
      'description': 'Set of 4 double-posted hard enamel pins with gold electroplating and individual laser serial numbers.',
      'stock_count': 50,
      'rating': 4.6,
      'is_featured': 0,
    },
    {
      'product_id': 'prod-007',
      'name': 'Demon Hunter Hand-Painted Resin Bust (1/4 Scale)',
      'category': 'Action Figures',
      'price': 229.00,
      'original_price': 275.00,
      'image_url': 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600',
      'description': 'Museum grade cold-cast resin statue with hand-finished gradient detailing and certificate of authenticity.',
      'stock_count': 3,
      'rating': 5.0,
      'is_featured': 1,
    },
    {
      'product_id': 'prod-008',
      'name': 'Pixel Legend Retro Gaming Backpack',
      'category': 'Apparel',
      'price': 79.99,
      'original_price': 99.00,
      'image_url': 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600',
      'description': 'Water-resistant cordura pack with programmable LED matrix front screen to display animated 8-bit sprites.',
      'stock_count': 12,
      'rating': 4.8,
      'is_featured': 0,
    },
  ];

  static const List<Map<String, dynamic>> defaultEvents = [
    {
      'event_id': 'evt-001',
      'title': 'Tokyo Anime Expo 2026',
      'description': 'The world’s largest gathering of animators, mangaka, voice actors, and global otaku fans at Big Sight.',
      'city_name': 'Tokyo',
      'venue_name': 'Tokyo Big Sight Exhibition Center',
      'latitude': 35.6298,
      'longitude': 139.7942,
      'event_date': 1785000000000,
      'ticket_link': 'https://anime-expo.tokyo/tickets',
      'banner_url': 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800',
      'is_bookmarked': 1,
    },
    {
      'event_id': 'evt-002',
      'title': 'San Diego International Comic-Con 2026',
      'description': 'Hall H exclusive reveals, Hollywood superhero panels, and the world famous Masquerade cosplay contest.',
      'city_name': 'San Diego',
      'venue_name': 'San Diego Convention Center',
      'latitude': 32.7071,
      'longitude': -117.1611,
      'event_date': 1786500000000,
      'ticket_link': 'https://comic-con.org/register',
      'banner_url': 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800',
      'is_bookmarked': 1,
    },
    {
      'event_id': 'evt-003',
      'title': 'Seoul Esports World Invitational',
      'description': '16 international powerhouse teams battle across 5 premier titles in an electric 15,000 seat stadium.',
      'city_name': 'Seoul',
      'venue_name': 'KSPO Dome Olympic Park',
      'latitude': 37.5195,
      'longitude': 127.1274,
      'event_date': 1787800000000,
      'ticket_link': 'https://seoul-esports.kr/tickets',
      'banner_url': 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800',
      'is_bookmarked': 0,
    },
  ];

  static const List<Map<String, dynamic>> defaultOrders = [
    {
      'order_id': 'FV-89241',
      'user_id': 'fan-01',
      'order_date': 1735000000000,
      'total_amount': 204.49,
      'items_summary': 'Chrono Blade Neon Katana (x1), Mecha G-Zero Enamel Pin (x1)',
      'shipping_address': 'Alex Mercer, 742 Evergreen Terrace, Sector 7-G, Neo Tokyo',
      'order_status': 'Completed',
    },
    {
      'order_id': 'FV-77104',
      'user_id': 'fan-01',
      'order_date': 1732000000000,
      'total_amount': 62.55,
      'items_summary': 'Cyber Otaku Oversized Hoodie [Night City] (x1)',
      'shipping_address': 'Alex Mercer, 742 Evergreen Terrace, Sector 7-G, Neo Tokyo',
      'order_status': 'Completed',
    },
  ];

  static const List<Map<String, dynamic>> defaultAuditLogs = [
    {
      'log_id': 'log-01',
      'action_type': 'CREATE',
      'entity_type': 'Merchandise',
      'description': 'Added new item "Chrono Blade Neon Katana (Replica 1:1)" with stock 6',
      'admin_email': 'admin@fandomverse.com',
      'timestamp': 1735100000000,
    },
    {
      'log_id': 'log-02',
      'action_type': 'UPDATE',
      'entity_type': 'Events',
      'description': 'Updated venue coords for "Tokyo Anime Expo 2026"',
      'admin_email': 'admin@fandomverse.com',
      'timestamp': 1735110000000,
    },
    {
      'log_id': 'log-03',
      'action_type': 'BROADCAST',
      'entity_type': 'Push Alert',
      'description': 'Broadcast alert "Summer Fandom Festival Tickets Live!" dispatched to 1,240 fans',
      'admin_email': 'admin@fandomverse.com',
      'timestamp': 1735120000000,
    },
  ];
}
